"""
src/api/routes.py
──────────────────
All FastAPI route definitions.

Endpoints implemented:
  GET  /health      — system status, model readiness, index stats, uptime
  POST /ingest      — upload PDF → parse → embed → index
  POST /query       — NL question → retrieve → generate → answer + sources
  GET  /documents   — list all indexed documents with chunk counts
  DELETE /delete    — remove a document from the index

/docs is auto-generated by FastAPI (Swagger UI).
"""

from __future__ import annotations

import os
import tempfile
import time
from pathlib import Path

from fastapi import APIRouter, File, Form, HTTPException, UploadFile, status

from src.api.schemas import (
    ChunkCounts,
    DeleteRequest,
    DeleteResponse,
    DocumentInfo,
    DocumentsResponse,
    HealthResponse,
    ComponentStatus,
    IngestResponse,
    QueryRequest,
    QueryResponse,
    RetrievalStats,
    SourceReference,
    ErrorResponse,
)

router = APIRouter()

# Track server start time for uptime reporting
_START_TIME = time.time()


# ══════════════════════════════════════════════════════════════════════════════
# GET /health
# ══════════════════════════════════════════════════════════════════════════════

@router.get(
    "/health",
    response_model=HealthResponse,
    summary="System health check",
    description=(
        "Returns model readiness, vector store stats (number of indexed documents, "
        "total chunk count, approximate index size), and server uptime."
    ),
    tags=["System"],
)
def health_check() -> HealthResponse:
    from src.config import get_settings
    from src.retrieval.vector_store import get_vector_store

    cfg = get_settings()
    components: dict[str, ComponentStatus] = {}

    # Check vector store
    try:
        store = get_vector_store()
        stats = store.get_stats()
        total_chunks = stats["total_chunks"]
        docs = store.list_indexed_documents()
        indexed_docs = len(docs)
        components["vector_store"] = ComponentStatus(
            status="ok",
            detail=f"ChromaDB — {total_chunks} chunks in '{cfg.default_collection}'",
        )
    except Exception as exc:
        total_chunks = 0
        indexed_docs = 0
        components["vector_store"] = ComponentStatus(
            status="unavailable", detail=str(exc)
        )

    # Check embedding model (lazy-load attempt)
    try:
        from src.ingestion.embedder import get_embedder
        emb = get_embedder()
        components["embedding_model"] = ComponentStatus(
            status="ok", detail=f"{cfg.embedding_model} (dim={emb.dim})"
        )
    except Exception as exc:
        components["embedding_model"] = ComponentStatus(
            status="unavailable", detail=str(exc)
        )

    # Check LLM (API key present)
    api_key_ok = bool(cfg.anthropic_api_key and cfg.anthropic_api_key.startswith("sk-"))
    components["llm"] = ComponentStatus(
        status="ok" if api_key_ok else "unavailable",
        detail=cfg.llm_model if api_key_ok else "ANTHROPIC_API_KEY not set",
    )

    # Check vision model
    components["vision_model"] = ComponentStatus(
        status="ok" if api_key_ok else "unavailable",
        detail=cfg.vision_model if api_key_ok else "ANTHROPIC_API_KEY not set",
    )

    # Estimate index size from ChromaDB persist dir
    try:
        chroma_dir = cfg.chroma_persist_dir
        size_bytes = sum(
            f.stat().st_size
            for f in chroma_dir.rglob("*")
            if f.is_file()
        )
        index_size_mb = round(size_bytes / (1024 * 1024), 2)
    except Exception:
        index_size_mb = 0.0

    overall = (
        "ok"
        if all(c.status == "ok" for c in components.values())
        else "degraded"
    )

    return HealthResponse(
        status=overall,
        version="1.0.0",
        uptime_seconds=round(time.time() - _START_TIME, 1),
        indexed_documents=indexed_docs,
        total_chunks=total_chunks,
        index_size_mb=index_size_mb,
        components=components,
    )


# ══════════════════════════════════════════════════════════════════════════════
# POST /ingest
# ══════════════════════════════════════════════════════════════════════════════

@router.post(
    "/ingest",
    response_model=IngestResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Ingest a PDF document",
    description=(
        "Upload a multimodal PDF. The pipeline extracts:\n"
        "- **Text** chunks (PyMuPDF)\n"
        "- **Table** chunks converted to Markdown (pdfplumber)\n"
        "- **Image** chunks summarised by Claude Vision VLM, then embedded\n\n"
        "All chunks are embedded with `sentence-transformers/all-MiniLM-L6-v2` "
        "and stored in ChromaDB. Returns ingestion summary with chunk counts by type "
        "and total processing time."
    ),
    tags=["Ingestion"],
    responses={
        400: {"model": ErrorResponse, "description": "Invalid file type"},
        413: {"model": ErrorResponse, "description": "File too large (> 100 MB)"},
        500: {"model": ErrorResponse, "description": "Ingestion failed"},
    },
)
async def ingest_document(
    file: UploadFile = File(
        ...,
        description="PDF file to ingest. Must be a valid PDF document.",
    ),
    collection: str = Form(
        "diagnostic_rag",
        description="ChromaDB collection name. Created if it does not exist.",
    ),
    use_vision: bool = Form(
        True,
        description=(
            "Whether to summarise images with Claude Vision. "
            "Set to false to skip image processing (faster but no image retrieval)."
        ),
    ),
) -> IngestResponse:
    # ── Validate ──────────────────────────────────────────────────────────────
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=400,
            detail="Only PDF files are accepted. Please upload a .pdf file.",
        )

    content = await file.read()

    if len(content) == 0:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    max_bytes = 100 * 1024 * 1024  # 100 MB
    if len(content) > max_bytes:
        raise HTTPException(
            status_code=413,
            detail=f"File size ({len(content) // (1024*1024)} MB) exceeds 100 MB limit.",
        )

    # ── Save to temp file ─────────────────────────────────────────────────────
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            delete=False, suffix=".pdf", prefix="rag_upload_"
        ) as tmp:
            tmp.write(content)
            tmp_path = Path(tmp.name)

        # ── Run pipeline ──────────────────────────────────────────────────────
        from src.ingestion.pipeline import IngestionPipeline

        pipeline = IngestionPipeline(collection=collection, use_vision=use_vision)
        result = await pipeline.run_async(tmp_path)

        # Determine status
        ingest_status = "success"
        if result.errors:
            ingest_status = "partial" if result.chunk_counts["total"] > 0 else "error"

        return IngestResponse(
            status=ingest_status,
            filename=file.filename,
            collection=result.collection,
            total_pages=result.total_pages,
            chunk_counts=ChunkCounts(**result.chunk_counts),
            processing_time_s=result.processing_time_s,
            warnings=result.errors[:10],  # cap at 10 warnings
            message=(
                f"Successfully indexed {result.chunk_counts['total']} chunks "
                f"({result.chunk_counts['text']} text, "
                f"{result.chunk_counts['table']} table, "
                f"{result.chunk_counts['image']} image) "
                f"from {result.total_pages} pages."
            ),
        )

    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Ingestion failed: {type(exc).__name__}: {exc}",
        )
    finally:
        if tmp_path and tmp_path.exists():
            tmp_path.unlink(missing_ok=True)


# ══════════════════════════════════════════════════════════════════════════════
# POST /query
# ══════════════════════════════════════════════════════════════════════════════

@router.post(
    "/query",
    response_model=QueryResponse,
    summary="Query the RAG system",
    description=(
        "Submit a natural language question. The system:\n"
        "1. Embeds the question with the same model used during ingestion\n"
        "2. Retrieves the top-k most relevant chunks from ChromaDB "
        "(text, table, and image-summary chunks)\n"
        "3. Assembles a structured context using the custom RAG prompt template\n"
        "4. Generates a grounded answer via Claude\n"
        "5. Returns the answer with full source references "
        "(filename, page, chunk type, relevance score, excerpt)\n\n"
        "Optionally filter retrieval to a specific `chunk_type_filter` "
        "(`text`, `table`, or `image`) to demonstrate modality-specific retrieval."
    ),
    tags=["Query"],
    responses={
        404: {"model": ErrorResponse, "description": "No documents indexed in collection"},
        500: {"model": ErrorResponse, "description": "Retrieval or generation failed"},
    },
)
async def query(request: QueryRequest) -> QueryResponse:
    from src.retrieval.retriever import get_retriever
    from src.retrieval.vector_store import get_vector_store

    # Check collection has data
    store = get_vector_store()
    count = store.collection_count(request.collection)
    if count == 0:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Collection '{request.collection}' is empty or does not exist. "
                "Please ingest a document first via POST /ingest."
            ),
        )

    try:
        retriever = get_retriever()
        result = retriever.query(
            question=request.question,
            top_k=request.top_k,
            collection=request.collection,
            chunk_type_filter=request.chunk_type_filter,
        )
    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Query failed: {type(exc).__name__}: {exc}",
        )

    sources = [
        SourceReference(
            filename=s.filename,
            page=s.page,
            chunk_type=s.chunk_type,
            score=s.score,
            excerpt=s.excerpt,
        )
        for s in result.sources
    ]

    rs = result.retrieval_stats
    return QueryResponse(
        question=result.question,
        answer=result.answer,
        sources=sources,
        retrieval_stats=RetrievalStats(
            total_retrieved=rs["total_retrieved"],
            by_type=rs["by_type"],
            collection=rs["collection"],
            top_k_requested=rs["top_k_requested"],
            llm_input_tokens=rs["llm_input_tokens"],
            llm_output_tokens=rs["llm_output_tokens"],
            llm_latency_ms=rs["llm_latency_ms"],
        ),
        latency_ms=result.latency_ms,
        model=result.model,
    )


# ══════════════════════════════════════════════════════════════════════════════
# GET /documents
# ══════════════════════════════════════════════════════════════════════════════

@router.get(
    "/documents",
    response_model=DocumentsResponse,
    summary="List all indexed documents",
    description=(
        "Returns a list of all documents currently indexed in the vector store, "
        "with per-document chunk counts broken down by type (text, table, image)."
    ),
    tags=["Management"],
)
def list_documents(
    collection: str = "diagnostic_rag",
) -> DocumentsResponse:
    from src.retrieval.vector_store import get_vector_store

    store = get_vector_store()
    docs = store.list_indexed_documents(collection)

    return DocumentsResponse(
        collection=collection,
        document_count=len(docs),
        documents=[
            DocumentInfo(
                filename=d["filename"],
                chunks=d["chunks"],
                total_chunks=d["total_chunks"],
            )
            for d in docs
        ],
    )


# ══════════════════════════════════════════════════════════════════════════════
# DELETE /delete
# ══════════════════════════════════════════════════════════════════════════════

@router.delete(
    "/delete",
    response_model=DeleteResponse,
    summary="Delete a document from the index",
    description=(
        "Remove all chunks belonging to a specific document filename from the "
        "vector store. The document can be re-ingested afterwards."
    ),
    tags=["Management"],
)
def delete_document(request: DeleteRequest) -> DeleteResponse:
    from src.retrieval.vector_store import get_vector_store

    store = get_vector_store()
    removed = store.delete_document(
        source=request.filename,
        collection=request.collection,
    )

    if removed == 0:
        return DeleteResponse(
            status="not_found",
            filename=request.filename,
            chunks_removed=0,
            message=f"No chunks found for '{request.filename}' in '{request.collection}'.",
        )

    return DeleteResponse(
        status="deleted",
        filename=request.filename,
        chunks_removed=removed,
        message=f"Removed {removed} chunks for '{request.filename}'.",
    )
